/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c.gltf --transform 
Files: c.gltf [76.9KB] > C:\Users\kohnk\OneDrive\Documents\misc coding projects\personal_website\kaleb-portfolio\src\models\C#\c-transformed.glb [42.08KB] (45%)
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c-e3a5d3e564a64fb0ab39665f44632520
Title: C#
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/c-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['C#_C#_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/c-transformed.glb')
