/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 javascript.gltf --transform 
Files: javascript.gltf [56.89KB] > C:\Users\kohnk\OneDrive\Documents\misc coding projects\personal_website\kaleb-portfolio\src\models\javascript\javascript-transformed.glb [11.53KB] (80%)
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/javascript-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.mat_3220964} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/javascript-transformed.glb')
