/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 python.gltf --transform 
Files: python.gltf [937.91KB] > C:\Users\kohnk\OneDrive\Documents\misc coding projects\personal_website\kaleb-portfolio\src\models\python\python-transformed.glb [74.93KB] (92%)
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-8be4a2579dd84586b915068e475073ee
Title: Python
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/python-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Python_Python_0.geometry} material={materials.Python} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/python-transformed.glb')
